### ISSUE TITLE
BUG RedirectorPage set to not show in search could result in destination page link being disallowed

### ISSUE THREAD

**Issue by muskie9** [tractorcow/silverstripe-robots#14]
We've found some cases where a shorter url is setup with a redirector page, and the redirect to url is actually disallowed as a result. I feel like this is an edge case based on the link that's returned by RedirectorPage, however it causes some indexing issues from an SEO perspective.

There is the config option to allow url's, however this seems inefficient as a code update would be required when a redirector is added to the cms. Curious on thoughts for this as for the time being we're having the client turn on the "Show in search" option for those redirector pages as that seems to be fine for a solution.

**Comment by tractorcow** [comment]
I think you're right; I think redirector pages probably shouldn't be included at all.
